include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/values/strings.dart

linter:
  rules:
    avoid_classes_with_only_static_members: false
    annotate_overrides: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    avoid_positional_boolean_parameters: false