include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/values/strings.dart
    - lib/values/app_constants.dart
    - lib/**/*.g.dart
    - lib/modules/ingredients_screen/widgets/custom/custom_date_picker.dart
    - lib/modules/ingredients_screen/widgets/custom/cupertino_picker.dart
    - lib/**/*.chopper.dart

linter:
  rules:
    avoid_classes_with_only_static_members: false
    annotate_overrides: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    avoid_positional_boolean_parameters: false